# Site
name: "The Advent Sentinel"
description: "<small>Looking for and hasting unto the coming of the day of God.</small>"
meta_description: "Looking for and hasting unto the coming of the day of God."
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl:
google_analytics: "UA-134169530-1"
mailchimp-list: "https://wangonya.us7.list-manage.com/subscribe?u=fe6da3bf1c0d2d23821df6d63&id=04b08f59dd"

# Authors
authors:
  ruth:
    name: Ruth Mwende
    display_name: Ruth Mwende
    gravatar: 1521fa2ac82530cf5d16e6a9dd1c7bb9
    # email: wowthemesnet@gmail.com
    web: https://reallifedevotionals.wordpress.com/
    # twitter: https://twitter.com/wowthemesnet
    description: "With all that the world experiences, it is not in vain. Through God's eyes, you can see everything from a different perspective of His Love towards fallen men and our need to be connected to the fountain of living waters - I bring that to us by God's grace."
  wangonya:
    name: Kinyanjui Wangonya
    display_name: Kinyanjui Wangonya
    gravatar: c79a61e9160d9cdac2932342d2210846
    description: "There is nothing that the great deceiver fears so much as that we shall become acquainted with his devices. <small> The Great Controversy by Ellen White, pg.516 par.3 </small>"
  alonzo:
    name: Alonzo Jones
    display_name: Alonzo Jones
    dp: "/assets/images/alonzo.jpg"
    description: "Higher than the highest human thought can reach is God's ideal for His children. Godliness—godlikeness—is the goal to be reached. <small> Education by Ellen White, pg.18 par.4 </small>"
  lucky:
    name: Lucky Omondi
    display_name: Lucky Omondi
    dp: "/assets/images/def.jpeg"
    description: "The warfare against self is the greatest battle that was ever fought. The yielding of self, surrendering all to the will of God, requires a struggle; but the soul must submit to God before it can be renewed in holiness. <small> Steps to Christ by Ellen White, pg.43 par.3 </small>"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-time-to-read

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
